baseURL: 'https://akvarun.github.io/'
defaultContentLanguage: en
languageCode: en
enableEmoji: true
title: Varun A K
theme: PaperMod

env: production

enableRobotsTXT: true

  
params:
  showToc: false
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  profileMode:
    enabled: true
    title: Bonjour.
    

  socialIcons:
    - name: Github
      url: 'https://github.com/akvarun'
    - name: Email
      url: 'mailto:akvarun08@gmail.com'

menu:
  main:
    - identifier: first
      name: Memoir
      url: /first
      weight: 1

    - identifier: notes
      name: Notes   
      url: /notes/
      weight: 2

    
