baseURL: "https://akvarun.github.io/'" 
languageCode: en-us
title: Varun 
theme: PaperMod 
enableEmoji: true

menu:
  main:
    - identifier: categories 
      name: categories
      url: /categories/
      weight: 10 
